language: ruby
rvm:
  - 2.2.2
before_install: gem install bundler -v 1.10.6
deploy:
  provider: rubygems
  api_key: $RUBYGEMS_API_KEY
  gem: westfield_swagger
  on:
    tags: true
    repo: westfieldlabs/westfield_swagger